# Матрицы

- **Матрица** - двумерный массив данных одного типа
- Для создания матрицы можно воспользоваться функцией **`matrix`**

In [20]:
matrix(1:8, nrow = 2, ncol = 4)

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

## Создание матриц

Предыдущая запись создания матрицы избыточна: можно указывать только количество либо столбцов, либо строк, второе значение вычисляется автоматически:

In [21]:
matrix(1:8, nrow = 2)

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [22]:
matrix(1:8, ncol = 4, byrow = TRUE)
# Аргумент byrow отвечает за заполнение матрицы не по столбцам (дефолтное), а по строкам

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

In [23]:
matrix(1:3, nrow = 2, ncol = 8)
# Если передаваемый вектор по размеру меньше, чем матрица, то он будет переписан, чтобы заполнить матрицу полностью

Warning message in matrix(1:3, nrow = 2, ncol = 8):
"длина данных [3] не является множителем количества строк [2]"

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    3    2    1    3    2    1    3   
[2,] 2    1    3    2    1    3    2    1

## Атрибут *`dim`*

Единственное (почти) отличие матрицы от вектора заключается в наличии атрибута `dim`, отвечающего за размерность

In [24]:
m <- matrix(1:8, nrow = 2)
dim(m)
m

[1] 2 4

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [25]:
dim(m) <- NULL
m
# Если убрать атрибут dim, то матрица превратится в обычный вектор

[1] 1 2 3 4 5 6 7 8

In [26]:
dim(m) <- c(2, 4)
m
# Восстановить размерность можно, присвоив dim вектор с соответствующими значениями

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

Матрицы в R "помнят", были они заполнены по строкам или по столбцам, поэтому `dim` корректно работает с `byrow = TRUE` матрицами

## Арифметические операторы

Действуют поэлементно (как и в векторах), с учётом правил переписывания:

In [11]:
m1 <- matrix(1:4, nrow = 2)
m2 <- matrix(c(1, 4, 5, 6), nrow = 2)
m1; m2
m1 + m2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 1    5   
[2,] 4    6

[,1] [,2]
[1,] 2     8  
[2,] 6    10

In [15]:
m1 + 5
# Можем добавлять число к матрице за счёт правил переписывания

[,1] [,2]
[1,] 6    8   
[2,] 7    9

In [16]:
m1 * 2
# Умножение матрицы на число происходит поэлементно

[,1] [,2]
[1,] 2    6   
[2,] 4    8

In [17]:
m1 * m2
# Умнжение матриц также поэлементно

[,1] [,2]
[1,] 1    15  
[2,] 8    24

In [12]:
m1 %*% m2
# Умножение матриц в контексте линейной алгебры происходит с помощью оператора %*%

[,1] [,2]
[1,] 13   23  
[2,] 18   34

Важно не забывать о правилах умножения матриц в алгебре. R - умный язык, но выходить за рамки алгебраических правил не умеет

## Индексирование матриц

Те же правила, что и для векторов, но с учётом двух размерностей:

In [13]:
m <- matrix(1:8, nrow = 2)
m
m[1, 3] # [строка, столбец]

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

[1] 5

In [20]:
m[2, ]
m[, 3]
# Можно опустить один из индексов, чтобы получить целый столбец / строку

[1] 2 4 6 8

[1] 5 6

In [15]:
m[1, ] <- c(1, 2)
m
# Можно осуществлять различные замены множеств элементов в матрицах

[,1] [,2] [,3] [,4]
[1,] 1    2    1    2   
[2,] 2    4    6    8

In [25]:
m[, -2] <- 1:6
m
# Замена всех столбцов кроме второго

[,1] [,2] [,3] [,4]
[1,] 1    2    3    5   
[2,] 2    4    4    6

## Схлопывание размерности

In [27]:
m <- matrix(1:8, nrow = 2)
m
ind <- c(1, 3, 4)
m[, ind]
# При передаче вектора чисел в качестве индекса получаем подматрицу

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

[,1] [,2] [,3]
[1,] 1    5    7   
[2,] 2    6    8

In [31]:
ind <- 3
m[, ind]
# Если же передать одно число, то произойдёт "схлопывание" размерности. Это значит, что вместо матрицы, состоящей
# из одного столбца, нам вернётся вектор

[1] 5 6

In [32]:
m[, ind, drop = FALSE]
# Избежать "схлопывания" можно с помощью установки аргументу drop значения FALSE

[,1]
[1,] 5   
[2,] 6

У `TRUE` и `FALSE` есть сокращения: `T` и `F`. Правда читаемость кода сильно ухудшается с их использованием

## Именованные матрицы: `rownames` / `colnames`

Вместо функции **`names`** у векторов, в связи с наличием размерностей, для матриц используются функции **`rownames`** и **`colnames`**

In [4]:
m <- matrix(1:8, nrow = 2)
m
rownames(m) <- c("row1", "row2")
colnames(m) <- paste0("column", 1:4) # Функция paste0 "склеивает" строку с каждым значением из указанного диапазона (удобно)
m

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

column1 column2 column3 column4
row1 1       3       5       7      
row2 2       4       6       8

In [7]:
m[, c("column1", "column2")]
# Можем обращаться к элементам по именам

column1 column2
row1 1       3      
row2 2       4

## Присоединение матриц: `rbind` / `cbind`

**`rbind`** (rowbind) - присоединение по строчкам, **`cbind`** (columnbind) - присоединение по столбцам

In [17]:
m1 <- matrix(1:4, nrow = 2)
m2 <- matrix(5:8, nrow = 2)
m1; m2
rbind(m1, m2)
cbind(m1, m2)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

[,1] [,2]
[1,] 1    3   
[2,] 2    4   
[3,] 5    7   
[4,] 6    8

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

При вызове справки по функциям **`rbind`** и **`cbind`**, можно увидеть, что одним из их аргументов является `...` (ellipsis). Данный аргумент позволяет передавать в функцию неограниченное число объектов:

In [19]:
cbind(m1, m2, rbind(m2, m1)[c(2, 3), ], matrix(1:4, nrow = 2))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    3    5    7    6    8    1    3   
[2,] 2    4    6    8    1    3    2    4

## Применение функций к матрице: `apply`

Три аргумента функции **`apply`**:
- Массив (матрица)
- Индекс (1 - по строкам, 2 - по столбцам)
- Функция

In [27]:
m <- matrix(1:25, 5)
m
f <- function(x) sum(x^2) # Функция считает сумму квадратов элементов вектора x
# Если в функции нет ключевого слова return, то функция вернёт результат последней операции
apply(m, 1, f)
apply(m, 2, f)

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

[1]  855  970 1095 1230 1375

[1]   55  330  855 1630 2655

In [28]:
apply(m, 1:2, function(i) if (i > 13) i else 13)
# Другой пример: функция заменят все элементы, которые меньше 13, на 13
# Здесь функция function - анонимная. Она прекратила существование после окончания работы функции apply

[,1] [,2] [,3] [,4] [,5]
[1,] 13   13   13   16   21  
[2,] 13   13   13   17   22  
[3,] 13   13   13   18   23  
[4,] 13   13   14   19   24  
[5,] 13   13   15   20   25

Хотя гораздо легче выполнить предыдущую задачу с помощью *логического индексирования*:

In [30]:
m[m <= 13] <- 13
m

[,1] [,2] [,3] [,4] [,5]
[1,] 13   13   13   16   21  
[2,] 13   13   13   17   22  
[3,] 13   13   13   18   23  
[4,] 13   13   14   19   24  
[5,] 13   13   15   20   25

## Популярные функции для матриц: `rowSums`, `rowMeans`, `colSums`, `colMeans`

Наиболее часто используемые операции по столбцам и по строкам это вычисление суммы (sum) и среднего значения (mean):

In [31]:
m <- matrix(1:25, 5)
m
rowSums(m)

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

[1] 55 60 65 70 75

In [32]:
all.equal(rowSums(m), apply(m, 1, sum))
# Проверим, что результаты совпадают

[1] TRUE

In [33]:
colMeans(m)

[1]  3  8 13 18 23

In [34]:
all.equal(colMeans(m), apply(m, 2, mean))

[1] TRUE